Repository CorgiTeamIncorporated/BookVerse, pull requests merged in 2020-12, with the labels that each got.

#14 add flask database models
  .gitignore
  database/schema.sql
  server/common/__init__.py
  server/common/database.py
  server/common/models/__init__.py
  server/common/models/_books.py
  server/common/models/_users.py
  server/config.py
  server/tests/__init__.py
  server/tests/test_01_simple_insertions.py
  server/tests/test_02_foreign_keys.py
  server/tests/utils.py
Labels: backend, basis, new feature

#13 add main page and page top bars templates
  server/templates/bookverse.html
  server/templates/css/font-awesome.min.css
  server/templates/fonts/FontAwesome.otf
  server/templates/fonts/fontawesome-webfont.svg
  server/templates/fonts/fontawesome-webfont.woff2
  server/templates/headerRegUser.css
  server/templates/headerRegUser.html
  server/templates/headerUnregUser.css
  server/templates/headerUnregUser.html
  server/templates/mainpage.css
Labels: basis, frontend

#17 add authorization and registration pages
  server/static/css/font-awesome.min.css
  server/static/enterPage.css
  server/static/fonts/FontAwesome.otf
  server/static/fonts/fontawesome-webfont.svg
  server/static/fonts/fontawesome-webfont.woff2
  server/static/headerRegUser.css
  server/static/headerUnregUser.css
  server/static/icons/Vk-logo.png
  server/static/icons/Yandex.png
  server/static/icons/logo-gmail1.png
  server/static/mainpage.css
  server/static/registrationPage.css
  server/templates/bookverse.html
  server/templates/enterPage.html
  server/templates/headerRegUser.html
  server/templates/headerUnregUser.html
  server/templates/registrationPage.html
Labels: basis, frontend, new feature

#20 add \login and \join pages to server
  .gitignore
  server/__main__.py
  server/blueprints/__init__.py
  server/blueprints/_login.py
  server/blueprints/_registration.py
  server/common/utils/__init__.py
  server/common/utils/validators/__init__.py
  server/common/utils/validators/_validators.py
  server/config.py
  server/static/enterPage.css
  server/static/headerUnregUser.css
  server/static/js/psw_toggling.js
  server/static/js/reg_data_checking.js
  server/static/registrationPage.css
  server/templates/enterPage.html
  server/templates/headerUnregUser.html
  server/templates/registrationPage.html
  server/tests/test_03_seq_validators.py
Labels: backend, basis, new feature

#23 update db and separate users declaration from schema.sql
  database/Dockerfile
  database/schema.sql
  database/users.sql
Labels: backend, database, enhancement

#26 code style impovements
  server/blueprints/_login.py
  server/blueprints/_registration.py
  server/common/models/__init__.py
  server/common/models/_books.py
  server/common/models/_users.py
  server/common/utils/validators/__init__.py
  server/common/utils/validators/_simple_validators.py
  server/common/utils/validators/_validators.py
  server/config.py
  server/tests/test_02_foreign_keys.py
  server/tests/test_03_seq_validators.py
  server/tests/utils.py
Labels: backend, enhancement

#25 improve css code
  server/static/enterPage.css
  server/static/headerRegUser.css
  server/static/headerUnregUser.css
  server/static/registrationPage.css
  server/templates/headerUnregUser.html
  server/templates/registrationPage.html
Labels: enhancement, frontend

#28 add home page to server
  database/schema.sql
  server/__main__.py
  server/blueprints/__init__.py
  server/blueprints/auth/__init__.py
  server/blueprints/auth/_join.py
  server/blueprints/auth/_login.py
  server/blueprints/auth/_logout.py
  server/blueprints/main/__init__.py
  server/blueprints/main/_home.py
  server/common/login_manager.py
  server/common/models/__init__.py
  server/common/models/_books.py
  server/common/models/_users.py
  server/static/headerUnregUser.css
  server/static/mainpage.css
  server/templates/bookverse.html
  server/templates/headerRegUser.html
  server/tests/test_02_foreign_keys.py
  server/tests/utils.py
  user.log
Labels: backend, basis, new feature

#29 delere user.log and update top-bar
  server/blueprints/auth/__init__.py
  server/templates/headerRegUser.html
  user.log
Labels: backend, enhancement

#33 Add book card
  server/static/bookCard.css
  server/templates/bookCard.html
Labels: basis, frontend

#35 Add author page
  server/static/authorPage.css
  server/templates/authorPage.html
Labels: basis, frontend

#37 review post implementation
  server/blueprints/main/__init__.py
  server/blueprints/main/_book.py
  server/templates/book_page.html
  server/templates/bookverse.html
  server/templates/enterPage.html
  server/templates/headerRegUser.html
  server/templates/registrationPage.html
  server/templates/searchPage.html
  server/templates/star_rating.html
Labels: backend, basis, database

#41 Issues/39
  server/blueprints/auth/__init__.py
  server/blueprints/auth/_join.py
  server/blueprints/auth/_login.py
  server/blueprints/auth/_logout.py
  server/blueprints/auth/_utils.py
  server/blueprints/main/__init__.py
  server/blueprints/main/_book.py
  server/blueprints/main/_home.py
  server/blueprints/main/_search.py
  server/blueprints/main/_utils.py
  server/common/database.py
  server/common/login_manager.py
  server/common/models/__init__.py
  server/common/models/_books.py
  server/common/utils/validators/__init__.py
  server/common/utils/validators/_simple_validators.py
  server/common/utils/validators/_validators.py
  server/main.py
  server/templates/book_list.html
  server/templates/headerRegUser.html
  server/templates/headerUnregUser.html
  server/templates/home_page.html
  server/templates/login_page.html
  server/templates/register_page.html
  server/templates/search_page.html
Labels: backend, basis, enhancement

#46 Issues/43
  .gitignore
  docker-compose.yml
  env/general.env
  env/vk_oauth.env.example
  server/app/blueprints/oauth/__init__.py
  server/app/blueprints/oauth/_client.py
  server/app/blueprints/oauth/_vk.py
  server/app/main.py
  server/app/requirements.txt
  server/app/templates/login_page.html
  server/app/templates/register_page.html
Labels: backend, basis, enhancement
